### ISSUE TITLE
Blender v2.79b not available though?

### ISSUE THREAD

**Issue by luzpaz** [OpenMandrivaAssociation/blender#1]
Regardless of https://github.com/OpenMandrivaAssociation/blender/blob/master/blender.spec#L12
I can't seem to find Blender 2.79b in http://abf-downloads.openmandriva.org/cooker/repository/SRPMS/main/release/

**Comment by abucodonosor** [comment]
please open bug reports @ https://issues.openmandriva.org/

**Comment by luzpaz** [comment]
Done: https://issues.openmandriva.org/show_bug.cgi?id=2426
